export const FRASES: string[] = [
  'Exoneraste todas las materias del semestre. Disfrutá este logro, porque refleja constancia, disciplina y muchísimo esfuerzo personal.',
  'Cerrar el semestre con todo exonerado no es suerte, es resultado de tu compromiso diario. Seguí así.',
  'Tu desempeño este semestre demuestra que vas construyendo grandes hábitos universitarios. Felicitaciones por el excelente resultado.',
  'Exonerar todas las materias requiere dedicación real. Hoy podés sentir orgullo por cada hora invertida durante el semestre.',
  'Terminaste el semestre sin finales pendientes. Excelente trabajo y gran demostración de responsabilidad académica.',
  'Cada exoneración representa esfuerzo sostenido. Haber logrado todas habla muy bien de tu capacidad y perseverancia.',
  'Lograste cerrar el semestre de la mejor manera posible. Felicitaciones y a seguir construyendo este gran camino universitario.',
  'Tus resultados muestran constancia y compromiso. Disfrutá este momento y seguí avanzando con la misma energía.',
  'Exonerar todo un semestre es un objetivo difícil. Haberlo conseguido merece reconocimiento y celebración.',
  'Tu dedicación durante el semestre tuvo recompensa. Excelente trabajo académico y gran ejemplo de organización.',
  'Felicitaciones por completar el semestre con todas las materias exoneradas. Tu esfuerzo realmente hizo la diferencia.',
  'Cerraste una etapa importante con resultados excelentes. Que este logro te motive para los próximos desafíos.',
  'Lo que conseguiste este semestre refleja disciplina, responsabilidad y muchas ganas de superarte constantemente.',
  'No todos logran exonerar todo un semestre. Valorá este resultado y seguí confiando en tus capacidades.',
  'Cada materia aprobada sin examen es fruto de trabajo constante. Excelente semestre y merecido reconocimiento.',
  'Tu rendimiento académico este semestre fue sobresaliente. Felicitaciones por mantener el compromiso hasta el final.',
  'Exoneraste todas las materias y eso merece celebrarse. Disfrutá el logro y preparate para seguir creciendo.',
  'Terminaste el semestre con excelentes resultados. El esfuerzo sostenido siempre termina dando recompensas importantes.',
  'Tus logros académicos muestran dedicación y constancia. Seguí avanzando con la misma actitud positiva.',
  'Este semestre fue una gran demostración de disciplina personal. Felicitaciones por el trabajo realizado.',
  'Exonerar todas las materias requiere mucho más que inteligencia: requiere constancia diaria. Excelente trabajo este semestre.',
  'Tu compromiso académico se reflejó claramente en los resultados. Felicitaciones por este gran cierre de semestre.',
  'Cada día de estudio valió la pena. Terminaste el semestre con un resultado realmente destacable.',
  'Felicitaciones por este logro académico tan importante. Tu esfuerzo constante quedó reflejado en cada materia exonerada.',
  'Haber exonerado todo el semestre habla de tu responsabilidad y capacidad para mantener objetivos claros.',
  'Excelente semestre. Tu dedicación y organización fueron claves para alcanzar este gran resultado académico.',
  'Hoy podés mirar atrás y reconocer todo lo que avanzaste. Felicitaciones por exonerar todas las materias.',
  'Tu esfuerzo silencioso durante el semestre terminó convirtiéndose en un resultado excelente. Muy buen trabajo.',
  'Exonerar todas las materias es reflejo de compromiso verdadero. Seguí construyendo este camino con confianza.',
  'Terminaste el semestre sin pendientes y con excelentes resultados. Disfrutá este logro totalmente merecido.',
  'Tu rendimiento demuestra que el trabajo constante siempre tiene recompensa. Felicitaciones por este gran semestre.',
  'Este logro académico es resultado de muchas pequeñas decisiones correctas tomadas durante el semestre.',
  'Felicitaciones por mantener el nivel durante todo el semestre. Tu constancia realmente marcó la diferencia.',
  'Exoneraste todas las materias y eso merece reconocimiento. Excelente trabajo y gran forma de cerrar el semestre.',
  'Tu desempeño académico este semestre fue ejemplar. Seguí confiando en tu capacidad para alcanzar metas importantes.',
  'Lograste uno de los mejores cierres posibles para un semestre universitario. Felicitaciones por el esfuerzo realizado.',
  'Cada exoneración representa horas de estudio y dedicación. Haber logrado todas es realmente destacable.',
  'Tus resultados reflejan organización, disciplina y perseverancia. Excelente semestre y merecidas felicitaciones.',
  'Exonerar todas las materias no ocurre por casualidad. Es consecuencia directa de tu compromiso académico.',
  'Terminaste el semestre demostrando gran responsabilidad y constancia. Seguí avanzando con esa misma mentalidad.',
  'Felicitaciones por este gran resultado académico. Tu esfuerzo constante quedó reflejado en cada evaluación.',
  'Cerraste el semestre con excelentes logros y mucho aprendizaje acumulado. Muy buen trabajo realizado.',
  'Exonerar todo un semestre requiere mantener el foco durante meses. Excelente trabajo y gran dedicación.',
  'Tu constancia académica dio resultados sobresalientes. Felicitaciones por completar el semestre con éxito total.',
  'Este semestre deja claro que vas por muy buen camino. Seguí construyendo sobre este gran avance.',
  'Cada materia exonerada representa un objetivo cumplido. Haber conseguido todas merece una felicitación especial.',
  'Excelente trabajo durante todo el semestre. Tus resultados reflejan compromiso y dedicación sostenida.',
  'Felicitaciones por alcanzar este logro académico tan importante. Que sea motivación para tus próximos desafíos.',
  'Tu desempeño demuestra que la disciplina diaria tiene resultados concretos. Excelente cierre de semestre.',
  'Exoneraste todas las materias y eso habla muy bien de tu esfuerzo, organización y compromiso académico.',
  'Terminaste el semestre con resultados excelentes y sin pendientes. Disfrutá este logro completamente merecido.',
  'Lo conseguido este semestre refleja trabajo constante y mucha perseverancia. Felicitaciones por el gran resultado.',
  'Mantener un rendimiento así durante todo el semestre no es fácil. Excelente trabajo académico.',
  'Felicitaciones por este semestre sobresaliente. Tu compromiso y dedicación fueron claves para alcanzar este resultado.',
  'Exonerar todas las materias es un logro importante. Seguí confiando en tu capacidad y manteniendo este nivel.',
  'Tus resultados muestran que el esfuerzo sostenido siempre vale la pena. Excelente semestre y felicitaciones.',
  'Cerraste el semestre de manera impecable. Que este logro te impulse hacia nuevos objetivos académicos.',
  'Excelente desempeño académico. Haber exonerado todas las materias refleja constancia y gran responsabilidad personal.',
  'Tu esfuerzo durante el semestre tuvo una recompensa enorme. Felicitaciones por este gran logro universitario.',
  'Exoneraste todo el semestre y eso merece reconocimiento. Disfrutá este momento y seguí creciendo académicamente.',
];

/** Elige una frase aleatoria que no esté en `usadas`. Resetea si ya se usaron todas. */
export function elegirFrase(usadas: number[]): { frase: string; idx: number; nuevasUsadas: number[] } {
  const total = FRASES.length;
  const pool = usadas.length >= total ? [] : usadas;
  const disponibles = Array.from({ length: total }, (_, i) => i).filter(i => !pool.includes(i));
  const idx = disponibles[Math.floor(Math.random() * disponibles.length)];
  return {
    frase: FRASES[idx],
    idx,
    nuevasUsadas: [...pool, idx],
  };
}
